name: "Docker"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Docker
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        node_version: [14.x]
        image_name: [ 'shveikinvlad/everkeep' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: shveikinvlad/everkeep:latest
